<?php
echo '<!DOCTYPE HTML><html>';
echo '<head><meta name="viewport" content="width=device-width, initial-scale=1"><link href="/css/main.css" rel="stylesheet"></head><body>';
echo '<div class=header>ueban music<form action="search.php"><center><input type=text id=poshuk name=q placeholder=Поиск value="'.$_GET["q"].'"><input type="submit" style="display:none;" value="пошук"></center></form></div><div class="content">';

$json = json_decode(file_get_contents('https://pipedapi.kavin.rocks/streams/'.$_GET["v"]));
echo '<div class=content><img src="'.$json->thumbnailUrl.'" width=100%><br>';
preg_match('/Auto-generated by YouTube/',$json->description,$matches);
echo '<center><audio controls><source src="'.array_reverse($json->audioStreams)[0]->url.'" type="audio/webm"></audio>';
if($matches){
$desc=explode('<br>',$json->description);
$title=explode(' · ',$desc[2]);
echo '<h2>'.$title[0].'</h2><h4>'.$title[1].'</h4></center>';
}else{
    echo '<h2>'.$json->title.'</h2><h4>'.$json->uploader.'</h4></center>';
}
echo '</div></body></html>';
?>
